# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: userservice-ingress
# spec:
#   rules:
#   - host: userservice.example.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: userservice-service
#             port:
#               number: 80